# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres:14.3
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    container_name: teslostoredb
    volumes:
      - ./postgres:/var/lib/postgresql/data
